apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  completions: 4 # 4 jobs will be launched in sequential manner
  template:
    spec:
      containers:
      - name: pi
        image: perl:5.34.0
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4 # after 4 tries if pod is getting failed it will not try again 

